steps:
  - label: ':docker: Docker build'
    key: build-image
    plugins:
      - ecr#v2.7.0:
          login: true
          account_ids: '014222686667'
          region: 'ap-southeast-1'
      - docker-compose#v3.9.0:
          build: plugin
          image-name: webpack-prerender-plugin
          image-repository: 014222686667.dkr.ecr.ap-southeast-1.amazonaws.com/opensource
          cache-from: plugin:014222686667.dkr.ecr.ap-southeast-1.amazonaws.com/opensource:latest
          push: plugin:014222686667.dkr.ecr.ap-southeast-1.amazonaws.com/opensource:latest

  - wait

  - label: ':jest: :puppeteer: Unit tests for Puppeteer renderer'
    command: ./scripts/test.sh
    plugins:
      - ecr#v2.7.0:
          login: true
          account_ids: '014222686667'
          region: 'ap-southeast-1'
      - docker-compose#v3.9.0:
          run: plugin
          cache-from: plugin:014222686667.dkr.ecr.ap-southeast-1.amazonaws.com/opensource:latest
          image-repository: 014222686667.dkr.ecr.ap-southeast-1.amazonaws.com/opensource
