steps:
  - label: ':docker: Docker build'
    key: docker
    plugins:
      - ecr#v2.7.0:
          login: true
          account_ids: '014222686667'
          region: 'ap-southeast-1'
      - docker-compose#v3.9.0:
          build: app
          image-repository: 014222686667.dkr.ecr.ap-southeast-1.amazonaws.com/opensource
          cache-from: 014222686667.dkr.ecr.ap-southeast-1.amazonaws.com/opensource/webpack-prerender-plugin:latest
          push: 014222686667.dkr.ecr.ap-southeast-1.amazonaws.com/opensource/webpack-prerender-plugin:latest
