steps:
  - label: ':docker: Docker build'
    key: build-image
    plugins:
      - ecr#v2.7.0:
          login: true
          account_ids: '014222686667'
          region: 'ap-southeast-1'
      - docker-compose#v3.9.0:
          build: plugin
          environment:
            - NPM_AUTH_TOKEN=${NPM_AUTH_TOKEN}
          image-name: webpack-prerender-plugin
          image-repository: 014222686667.dkr.ecr.ap-southeast-1.amazonaws.com/opensource
          cache-from: plugin:014222686667.dkr.ecr.ap-southeast-1.amazonaws.com/opensource:latest
          push: plugin:014222686667.dkr.ecr.ap-southeast-1.amazonaws.com/opensource:latest

  - wait

  - label: ':jest: :puppeteer: Unit tests for Puppeteer renderer'
    command: ./scripts/test.sh
    key: puppeteer-renderer-unit-test
    plugins:
      - ecr#v2.7.0:
          login: true
          account_ids: '014222686667'
          region: 'ap-southeast-1'
      - docker-compose#v3.9.0:
          run: plugin
          environment:
            - NPM_AUTH_TOKEN=${NPM_AUTH_TOKEN}
          cache-from: plugin:014222686667.dkr.ecr.ap-southeast-1.amazonaws.com/opensource:latest
          image-repository: 014222686667.dkr.ecr.ap-southeast-1.amazonaws.com/opensource

  - block: 'Release @webpack-prerender-plugin/puppeteer-renderer :rocket:'
    key: puppeteer-release
    depends_on: puppeteer-renderer-unit-test
    fields:
      - select: 'Version'
        key: semantic-version
        default: patch
        options:
          - label: patch
            value: patch
          - label: minor
            value: minor
          - label: major
            value: major

  - label: ':construction_worker: Preparing release environment'
    command: make prepare
    depends_on: puppeteer-release
    key: prepare-puppeteer-release
